### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by Siegrift** [api3dao/api3-dao-dashboard#106]
I'd like dashboard to be tested e2e as well...

Unfortunately, due to time pressure only simple tests were written, but I'd like to add more :) 

However, I think our tests (for such a simple page) should be under 15 minutes and we shouldn't complicate things and focus on the most importants parts and user flows.

## This includes

- [x] Initial setup = Done in https://github.com/api3dao/api3-dao-dashboard/pull/126
- [x] Test dashboard flow = Done in https://github.com/api3dao/api3-dao-dashboard/pull/126
- [x] Implement code changes allowing switching accounts in e2e tests (read description of https://github.com/api3dao/api3-dao-dashboard/pull/126)
- [x] #196
- [x] #157
- [ ] Test notifications (I think this can just be added to dashboard tests to save execution time)
- [x] #181
- [ ] Test active proposals page (voting, navigation to invalid proposal page, after epoch length passed proposal should move to history page)
- [ ] Test history proposals page (execute, invalid proposal details page)
- [ ] Delegation + treasury
- [ ] Test mobile version (probably just a bit to save execution time)
- [ ] We have a lot of annoying styling special cases. I think it's worth adding some visual tests as well (https://docs.cypress.io/guides/tooling/visual-testing#Functional-vs-visual-testing)

**Comment by Siegrift** [comment]
There are many e2e tests for multiple user flows and there is little need for the ones in the issue checklist. Some points are even outdated (e.g. we have visual tests as well).
