### ISSUE TITLE
Rebrand DAO Dashboard

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#506]
### Debts

- [x] Replace the Help tooltip in the New Proposal modal with an external link to docs ([PR](https://github.com/api3dao/api3-dao-dashboard/pull/515))
- [x] Remove code temporarily added in [#499] and [#502] ([PR](https://github.com/api3dao/api3-dao-dashboard/pull/517))
- [x] Fix console errors ([PR](https://github.com/api3dao/api3-dao-dashboard/pull/516))
- [x] Update text in the modals ([UX/UI task](https://github.com/api3dao/tasks/issues/1535))
- [x] Update design of the "This proposal is potentially malicious." warning ([design](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=10535-221092&node-type=frame&t=m5VXclWhl9K97LvM-0), [PR](https://github.com/api3dao/api3-dao-dashboard/pull/518))
- [x] Update styles of unconnected state of the Proposal details page ([UX/UI task](https://github.com/api3dao/tasks/issues/1533))
- [x] Adjust Vote states after they are updated in the design ([UX/UI task](https://github.com/api3dao/tasks/issues/1546))
- [x] Remove unused code (unused icons, CSS variables, BorderedBox component ... )
- [x] Connect Wallet button might be fitted into the header ([UX/UI task](https://github.com/api3dao/tasks/issues/1554))
- [x] Fix 404 page breakpoints ([design](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=10647-109961&t=3NwQckIt9dmDzYfu-1))

**Comment by peterjurco** [comment]
@PrenaamD The every point from the ticket was done in a separate PR, all of them mentioning this ticket so you should see it here ⤴

**Comment by PrenaamD** [comment]
@peterjurco it seems that the "voted for/against" icon is not displayed

![Image](https://github.com/user-attachments/assets/717e347d-79c1-45b9-8c9c-ff2a5754f150)

I am testing locally by reusing the code from this commit [Add testing capabilities](https://github.com/api3dao/api3-dao-dashboard/pull/502/commits/61437faf266b71972cefc4f98948ae7bf53fc9f4)

I will be posting feedback progressively

**Comment by PrenaamD** [comment]
Regarding the Modals text, It should be "How many API3 tokens would you like to stake?" according to [design](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-107824&t=YUNZkFWk7zaGH9tq-4) instead of "How many tokens would you like to stake?"
Same applies to 

- How many tokens would you like to unstake
- How many tokens would you like to withdraw/deposit

**Comment by peterjurco** [comment]
> it seems that the "voted for/against" icon is not displayed

Good catch. I accidentally removed those icons in the cleanup PR. I will be adding the fixes from your review to the [fixes-after-qa](https://github.com/api3dao/api3-dao-dashboard/compare/rebrand...fixes-after-qa) branch.

**Comment by peterjurco** [comment]
> Regarding the Modals text, It should be "How many API3 tokens would you like to stake?" according to [design](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-107824&t=YUNZkFWk7zaGH9tq-4) instead of "How many tokens would you like to stake?"

Yeah, that's correct. I am adding "API3" prefix to those modal titles

**Comment by PrenaamD** [comment]
> I will be posting feedback progressively

Done.

**Comment by peterjurco** [comment]
@PrenaamD both issues you uncovered above have been fixed
