### ISSUE TITLE
Helper icon showing information in tooltip

### ISSUE THREAD

**Issue by Siegrift** [api3dao/api3-dao-dashboard#86]
As discussed on last call we want to add `?` icons with help displayed on hover. Consult the designs and slack for more info.

## This includes

- [ ] For governance page (design + checklist text ready in figma)
- [x] For staking page (checklists not ready), also see slack: https://api3workspace.slack.com/archives/C020RCCC3EJ/p1624206508014700
- [x] New proposal form (design + text ready in https://api3workspace.slack.com/archives/C020RCCC3EJ/p1624208562024800)

(If there are things that are written as "not ready" be sure to check them up, because they might have been updated/added in the meantime)

**Comment by Siegrift** [comment]
There is one last helper icon in new proposal form which doesn't seem to be needed.
All other helper icons are implemented.
